server:
  port: 9400
spring:
  application:
    name: cloud-eureka1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000