server:
  port: 9403
spring:
  application:
    name: eureka-service
  security:
    user:
      name: root
      password: root
#Eureka实例名，集群中根据这里相互识别
eureka:
    client:
      #是否开启注册服务，因为这里如果为true表示自己注册自己，而自己就是一个服务注册方，没必要自己注册自己
      register-with-eureka: false
      #是否拉取服务列表，这里我只提供服务给别的服务。
      fetch-registry: false

