server:
  port: 9407
spring:
  application:
    name: cloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9400/eureka/
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    # 给服务配置路由
    cloud-feign:
      path: /feign/**
  ignored-services: cloud-feign
  prefix: /proxy
  #配置过滤敏感的请求头信息，设置为空就不会过滤
  sensitive-headers: Cookie,Set-Cookie,Authorization
  #设置为true重定向是会添加host请求头
  add-host-header: true
  filterClassName:
    filter:
      disable: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
