server:
  port: 9405
spring:
  application:
    name: cloud-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试机制
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9400/eureka
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds
#断路器的超时时间需要大于Ribbon的超时时间，不然不会触发重试

