server:
  port: 9401
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mufeng07/cloud/
          search-paths: /cloud-config/config-repo
          username: mufeng07
          password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9400/eureka
